# Generated by Django 5.2.6 on 2026-04-08 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(help_text='e.g. A-01, B-05', max_length=10, unique=True)),
                ('location', models.CharField(help_text='e.g. Ground Floor, Level 2', max_length=100)),
                ('status', models.CharField(choices=[('free', 'Free'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='free', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slot_number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(db_index=True, max_length=5, unique=True)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('date', models.DateField(help_text='Booking date')),
                ('start_time', models.TimeField(help_text='Booking start time')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='bookings.parkingslot')),
            ],
            options={
                'ordering': ['-reserved_at'],
            },
        ),
    ]
